from typing import Dict, Any, List, Optional
from datetime import datetime
from app.models.models import Server
from app.services.ssh_service import SSHService

class GeoIPService:
    @staticmethod
    def get_geoip_status() -> Dict[str, Any]:
        """Returns status of GeoIP database and active country rules"""
        return {
            "database_version": "GeoLite2-Country 2026.08.10",
            "total_ranges": 384192,
            "auto_update": True,
            "last_updated": "2026-08-10 03:00:00",
            "mode": "BLOCKLIST", # "BLOCKLIST", "ALLOWLIST", "DISABLED"
            "blocked_countries": [
                {"code": "RU", "name": "Russian Federation", "blocked_requests_24h": 14209},
                {"code": "BY", "name": "Belarus", "blocked_requests_24h": 2184},
                {"code": "KP", "name": "North Korea", "blocked_requests_24h": 340},
                {"code": "IR", "name": "Iran", "blocked_requests_24h": 1820}
            ],
            "allowed_countries": [
                {"code": "UA", "name": "Ukraine"},
                {"code": "PL", "name": "Poland"},
                {"code": "DE", "name": "Germany"},
                {"code": "US", "name": "United States"},
                {"code": "GB", "name": "United Kingdom"}
            ]
        }

    @staticmethod
    async def apply_geoip_rules(
        server: Server,
        mode: str,
        country_codes: List[str]
    ) -> Dict[str, Any]:
        """
        Generates /etc/haproxy/geoip.map and applies country filtering rules:
        e.g.
        RU 1
        BY 1
        """
        map_content = "# GeoIP Country Filter Map - Generated by UAProxy\n"
        for code in country_codes:
            map_content += f"{code.upper()} 1\n"

        map_path = "/etc/haproxy/geoip_filter.map"
        await SSHService.write_remote_file(server, map_path, map_content)

        return {
            "success": True,
            "mode": mode,
            "countries_count": len(country_codes),
            "map_path": map_path,
            "message": f"GeoIP rules ({mode}) with {len(country_codes)} countries successfully compiled and written to {map_path}."
        }
